name: flutterkaigi2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_shaders: ^0.1.2
  fluttershow_base: ^1.1.1
  fluttershow_keynote: ^1.1.0
  hooks_riverpod: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/background.frag
